name: Sync from GitLab to GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜（UTC 时间）运行

jobs:
  clone-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Clone GitLab repository
        run: |
          git clone https://gitlab.com/Misaka-blog/warp-script.git
        shell: bash

      - name: Git push assets to "Misaka-blog" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b Misaka-blog
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin Misaka-blog

