name: Sync from GitLab to GitHub  
  
on:  
  workflow_dispatch:  
  schedule:  
    - cron: '0 0 * * *'  # 每天午夜（UTC 时间）运行  
  
permissions:  
  contents: write  
  packages: write  
  actions: write  
  
jobs:  
  clone-and-sync:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Set up Git  
        run: |  
          git config --global user.name 'GitHub Action'  
          git config --global user.email 'action@github.com'  
  
      - name: Clone GitLab repository  
        run: |  
          git clone https://gitlab.com/Misaka-blog/warp-script.git gitlab-repo  
        shell: bash  
  
      - name: Checkout to new branch and push to GitHub  
        working-directory: gitlab-repo  
        run: |  
          git checkout -b Misaka-blog  
          git add .  
          git commit -m "${{ env.RELEASE_NAME }}"  
          git remote add github "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"  
          git push -f -u github HEAD:Misaka-blog
        env:  
          RELEASE_NAME: "Released on $(date +%Y%m%d%H%M)"  
