name: Sync from gitlab.com/fscarmen to GitHub  
  
on:  
  workflow_dispatch:  
  schedule:  
    - cron: '0 0 * * *'  # 每天午夜（UTC 时间）运行  
  
permissions:  
  contents: write  
  packages: write  
  actions: write  
  
jobs:  
  clone-and-sync:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Set up Git  
        run: |  
          git config --global user.name 'github-actions[bot]'  
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'  
  
      - name: Clone GitLab repository  
        run: |  
          git clone https://gitlab.com/fscarmen/warp.git gitlab-repo  
        shell: bash  
  
      - name: Checkout to new branch and push to GitHub  
        run: |  
          cd gitlab-repo || exit 1
          rm -rf .git .github
          git init
          git checkout -b fscarmen
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin fscarmen
        env:  
          RELEASE_NAME: "Released on $(date +%Y%m%d%H%M)"  
